#!/bin/bash
set -e
TVAULT_V=3.0.73.tar.gz
TVAULTAPP=192.168.25.20
HORIZON_PATH=/usr/share/openstack-dashboard/
WebServer=apache2
juju-log "pip install --no-deps http://$TVAULTAPP:8081/packages/python-workloadmgrclient-$TVAULT_V &> /dev/null"
#pip install --no-deps http://$TVAULTAPP:8081/packages/python-workloadmgrclient-$TVAULT_V &> /dev/null
hostname
pip install --no-deps http://$TVAULTAPP:8081/packages/python-workloadmgrclient-$TVAULT_V 
        if [ $? -eq 0 ]; then
                juju-log "Installing python-workloadmgrclient-$TVAULT_V"
        else
                juju-log "Error : pip install http://$TVAULTAPP:8081/packages/python-workloadmgrclient-$TVAULT_V"
                exit 1
        fi
        juju-log "pip install --no-deps http://$TVAULTAPP:8081/packages/tvault-horizon-plugin-$TVAULT_V &> /dev/null"
        #pip install --no-deps http://$TVAULTAPP:8081/packages/tvault-horizon-plugin-$TVAULT_V &> /dev/null
        pip install --no-deps http://$TVAULTAPP:8081/packages/tvault-horizon-plugin-$TVAULT_V 
        if [ $? -eq 0 ]; then
                juju-log "Installing tvault-horizon-plugin-$TVAULT_V"
        else
                juju-log "Error : pip install  http://$TVAULTAPP:8081/packages/tvault-horizon-plugin-$TVAULT_V"
                exit 1
        fi
juju-log "Workloadmanager client and tvault-horizon-plugin are installed....configure is next step"
status-set active
