#!/bin/bash
set -e
TVAULT_V=$1
TVAULTAPP=$2
HORIZON_PATH=$3
WebServer=$4

juju-log "GOT the value from config $TVAULT_V"
juju-log "GOT the value from config $TVAULTAPP"
juju-log "GOT the value from config $HORIZON_PATH"
juju-log "GOT the value from config $WebServer"

pip install --no-deps http://$TVAULTAPP:8081/packages/python-workloadmgrclient-$TVAULT_V &> /dev/null
        if [ $? -eq 0 ]; then
                juju-log "Installing python-workloadmgrclient-$TVAULT_V"
        else
                juju-log "Error : pip install http://$TVAULTAPP:8081/packages/python-workloadmgrclient-$TVAULT_V"
                exit 1
        fi
        pip install --no-deps http://$TVAULTAPP:8081/packages/tvault-horizon-plugin-$TVAULT_V &> /dev/null
        if [ $? -eq 0 ]; then
                juju-log "Installing tvault-horizon-plugin-$TVAULT_V"
        else
                juju-log "Error : pip install  http://$TVAULTAPP:8081/packages/tvault-horizon-plugin-$TVAULT_V"
                exit 1
        fi
juju-log "Workloadmanager client and tvault-horizon-plugin are installed....configure is next step"
